version: "3.5"
services:

  ir:
    image: ismaelvarez/instalacionconectada:ir
    hostname: ir
    container_name: ir
    privileged: true
    volumes:
      - ./modules/ir/config/21064185.xml:/root/catkin_ws/src/optris_drivers/config/generic.xml
      - ./modules/ir/config/optris_imager.yaml:/tmp/.ros/camera_info/optris_imager.yaml
      - /dev/bus/:/dev/bus/:ro
      - /dev/serial:/dev/serial:ro
    
    devices:
      - /dev:/dev
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://${HOSTNAME}:11311/
      - ROS_HOSTNAME=${HOSTNAME}
    command: ["/bin/bash", "-c", "source /opt/ros/melodic/setup.bash && source /root/catkin_ws/devel/setup.bash && roslaunch --wait gara_infrared_camera gara_infrared_camera.launch temperatureMin:=20 temperatureMax:=50"]
        
  thermal_processing:
    image: ismaelvarez/instalacionconectada:thermal-processing
    hostname: thermal_processing
    container_name: thermal
    depends_on:
      - ir
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://${HOSTNAME}:11311/
      - ROS_HOSTNAME=${HOSTNAME}
    command: ["/bin/bash", "-c", "source /opt/ros/melodic/setup.bash && source /root/catkin_ws/devel/setup.bash && roslaunch --wait thermal_processing thermal_processing.launch"]

  web_server:
    image: ismaelvarez/instalacionconectada:web-server
    hostname: web_server
    container_name: web_server
    
    network_mode: host
    depends_on:
      - ir
    environment:
      - ROS_MASTER_URI=http://${HOSTNAME}:11311/
      - ROS_HOSTNAME=${HOSTNAME}
    command: ["/bin/bash", "-c", "source /opt/ros/melodic/setup.bash && source /root/catkin_ws/devel/setup.bash  && rosrun web_video_server web_video_server _port:=8090"]
    
  is:
    image: ros-is:latest
    hostname: is
    container_name: is
    volumes:
      - ./modules/is/config/config.yaml:/root/is-workspace/config/config.yaml
    
    network_mode: host
    depends_on:
      - ir
      - telemetry
    environment:
      - ROS_MASTER_URI=http://${HOSTNAME}:11311/
      - ROS_HOSTNAME=${HOSTNAME}
    command: ["/bin/bash", "-c", "source /opt/ros/melodic/setup.bash && source /root/catkin_ws/devel/setup.bash && source /root/is-workspace/install/setup.bash && /root/is-workspace/install/is-core/install/integration-service /root/is-workspace/config/config.yaml"]
    
  telemetry:
    image: ismaelvarez/instalacionconectada:gara-telemetry
    hostname: telemetry
    container_name: telemetry
    
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://${HOSTNAME}:11311/
      - ROS_HOSTNAME=${HOSTNAME}
    command: ["/bin/bash", "-c", "source /opt/ros/melodic/setup.bash && source /root/catkin_ws/devel/setup.bash && rosrun --wait gara_telemetry telemetry.py"]
        
